global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'trending-service'
    static_configs:
      - targets: ['app:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s